spring.application.name=forrage-app

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/forage_eau
spring.datasource.username=postgres
spring.datasource.password=HARIVONY
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# File size
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
